[build]
    command = "npm run build"
    functions = "functions"
    publish = "build"
    targetPort = 3000

[dev]
    targetPort = 3000

[[redirects]]
  from = "/<path-to-access-cors-url>"
  to = "<cross-origin-url>"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"